service: default
runtime: go122

env_variables:
  GOLANGORG_CHECK_COUNTRY: true
  TOUR_ANALYTICS: |
    <!-- analytics no configurat per evitar lios amb cookies -->

default_expiration: "7d"

handlers:

# Keep these static file handlers in sync with local.go.
# They're here for improved latency across global regions.
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  secure: always
- url: /content/img
  static_dir: content/img
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /.well-known
  static_dir: well-known
  secure: always

# This is here to redirect all HTTP traffic to an HTTPS URL
# with the same path.
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  max_instances: 1
  min_instances: 0
